### PR TITLE
Update fsharp sha

### PR DESCRIPTION
**Pull request by karajas**
This updates the fsharp sha to 7ef93f807e635a342c8ee6a4411213b78a68bb2d. This was determined from https://github.com/Microsoft/visualfsharp/releases/tag/Visual-Studio-2017-Version-15.5 which has the matching package version determined from the cli commit.

### CODE REVIEW

**Comment by weshaggard** [comment]
@karajas that doesn't look like the correct sha.

Based on https://github.com/dotnet/cli/blob/5e8add2190a75e5578bf6ac90dc6dfee8c69e578/build/DependencyVersions.props#L9.

```
--a-- WAMD64 APP   -     2017.11.4.1 shp  4,373,472 12-21-2017 fsharp.core.dll
        Language        0x0000 (Language Neutral)
        CharSet         0x04b0 Unicode
        OleSelfRegister Disabled
        CompanyName     Microsoft Corporation
        FileDescription FSharp.Core.dll
        OriginalFilenam FSharp.Core.dll
        ProductName     Microsoft« F#
        ProductVersion  4.4.1.0
        FileVersion     2017.11.4.1
        LegalCopyright  ⌐ Microsoft Corporation.  All Rights Reserved.
        Comments        FSharp.Core.dll
        OleSelfRegister Disabled
```

It looks like it is a build from Nov.

**Comment by karajas** [comment]
I think this is still the right sha, confirming with the build that shipped it.

**Comment by karajas** [comment]
This is still the right sha, the other sha was the internal merge commit for this commit.

**Comment by weshaggard** [comment]
Sounds good lets get these changes in.

**Pull request merged**
